"""
Seed accounts for demo mode. All demo accounts share the password
'demo1234' so judges/testers can log in instantly. Passwords are hashed at
seed time in seed_data.py -- nothing here is stored as-is in the database.
"""

DEMO_PASSWORD = "demo1234"

DEMO_FARMERS = [
    {
        "name": "Ramesh Kumar",
        "email": "ramesh@cropwise.demo",
        "phone": "+91 98765 43210",
        "location": "Bilaspur",
        "latitude": 22.0797, "longitude": 82.1409,
        "crops": ["Tomato", "Paddy (Rice)", "Soybean"],
        "preferred_language": "hi",
        "rating": 4.6,
        "fpo_group": "Bilaspur Kisan Producer Company",
    },
    {
        "name": "Sunita Verma",
        "email": "sunita@cropwise.demo",
        "phone": "+91 98111 22334",
        "location": "Raigarh",
        "latitude": 21.8974, "longitude": 83.3950,
        "crops": ["Onion", "Wheat", "Maize"],
        "preferred_language": "hi",
        "rating": 4.8,
        "fpo_group": None,
    },
    {
        "name": "Manoj Sahu",
        "email": "manoj@cropwise.demo",
        "phone": "+91 97654 11223",
        "location": "Durg",
        "latitude": 21.1904, "longitude": 81.2849,
        "crops": ["Maize", "Chana (Gram)", "Groundnut"],
        "preferred_language": "en",
        "rating": 4.3,
        "fpo_group": "Durg Farmer Collective",
    },
    # ---- additional demo farmers (appended, existing indices 0-2 unchanged
    # so every hardcoded farmers[0..2] reference elsewhere in seed_data.py
    # keeps working) ----
    {
        "name": "Preeti",
        "email": "preeti@cropwise.demo",
        "phone": "+91 98222 10101",
        "location": "Bilaspur",
        "latitude": 22.0797, "longitude": 82.1409,
        "crops": ["Tomato", "Onion"],
        "preferred_language": "hi",
        "rating": 4.7,
        "fpo_group": "Bilaspur Kisan Producer Company",
    },
    {
        "name": "Dilip Nirmalkar",
        "email": "dilip@cropwise.demo",
        "phone": "+91 98333 20202",
        "location": "Rajnandgaon",
        "latitude": 21.0972, "longitude": 81.0388,
        "crops": ["Soybean", "Chana (Gram)", "Wheat"],
        "preferred_language": "hi",
        "rating": 4.4,
        "fpo_group": "Rajnandgaon Producer Company",
    },
    {
        "name": "Kavita Patel",
        "email": "kavita@cropwise.demo",
        "phone": "+91 98444 30303",
        "location": "Mahasamund",
        "latitude": 21.1093, "longitude": 82.0980,
        "crops": ["Paddy (Rice)", "Maize"],
        "preferred_language": "en",
        "rating": 4.5,
        "fpo_group": None,
    },
    {
        "name": "Ganesh Yadav",
        "email": "ganesh@cropwise.demo",
        "phone": "+91 98555 40404",
        "location": "Korba",
        "latitude": 22.3595, "longitude": 82.7501,
        "crops": ["Wheat", "Paddy (Rice)", "Groundnut"],
        "preferred_language": "hi",
        "rating": 4.2,
        "fpo_group": "Korba Farmer Collective",
    },
    {
        "name": "Anita Dewangan",
        "email": "anita@cropwise.demo",
        "phone": "+91 98666 50505",
        "location": "Ambikapur",
        "latitude": 23.1200, "longitude": 83.1950,
        "crops": ["Maize", "Chana (Gram)"],
        "preferred_language": "hi",
        "rating": 4.6,
        "fpo_group": None,
    },
    {
        "name": "Prakash Baghel",
        "email": "prakash@cropwise.demo",
        "phone": "+91 98777 60606",
        "location": "Jagdalpur",
        "latitude": 19.0748, "longitude": 82.0198,
        "crops": ["Paddy (Rice)", "Groundnut", "Soybean"],
        "preferred_language": "en",
        "rating": 4.1,
        "fpo_group": "Bastar FPO",
    },
    {
        "name": "Meena Sinha",
        "email": "meena@cropwise.demo",
        "phone": "+91 98888 70707",
        "location": "Bilha",
        "latitude": 22.1500, "longitude": 82.0500,
        "crops": ["Tomato", "Onion", "Wheat"],
        "preferred_language": "hi",
        "rating": 4.9,
        "fpo_group": "Bilaspur Kisan Producer Company",
    },
]

DEMO_BUYERS = [
    {
        "company_name": "FreshFoods Processing Pvt. Ltd.",
        "email": "freshfoods@cropwise.demo",
        "phone": "+91 90000 11111",
        "location": "Raipur",
        "latitude": 21.2514, "longitude": 81.6296,
        "buyer_type": "processor",
        "verification_status": "verified",
        "reliability_score": 92.0,
        "payment_history_score": 95.0,
        "crops_of_interest": ["Tomato", "Onion", "Potato"],
    },
    {
        "company_name": "GreenBasket Retail",
        "email": "greenbasket@cropwise.demo",
        "phone": "+91 90000 22222",
        "location": "Bilaspur",
        "latitude": 22.0797, "longitude": 82.1409,
        "buyer_type": "retailer",
        "verification_status": "verified",
        "reliability_score": 88.0,
        "payment_history_score": 90.0,
        "crops_of_interest": ["Tomato", "Potato", "Onion", "Maize"],
    },
    {
        "company_name": "AgriExport India",
        "email": "agriexport@cropwise.demo",
        "phone": "+91 90000 33333",
        "location": "Durg",
        "latitude": 21.1904, "longitude": 81.2849,
        "buyer_type": "exporter",
        "verification_status": "verified",
        "reliability_score": 81.0,
        "payment_history_score": 84.0,
        "crops_of_interest": ["Soybean", "Chana (Gram)", "Groundnut", "Paddy (Rice)"],
    },
    {
        "company_name": "Chhattisgarh Wholesale Traders",
        "email": "wholesale@cropwise.demo",
        "phone": "+91 90000 44444",
        "location": "Korba",
        "latitude": 22.3595, "longitude": 82.7501,
        "buyer_type": "wholesaler",
        "verification_status": "pending",
        "reliability_score": 68.0,
        "payment_history_score": 72.0,
        "crops_of_interest": ["Wheat", "Paddy (Rice)", "Maize"],
    },
    # ---- additional demo buyers (appended, existing indices 0-3 unchanged
    # so every hardcoded buyers[0..3] reference elsewhere in seed_data.py
    # keeps working) ----
    {
        "company_name": "Kisan Limited",
        "representative": "Riya Malhotra — Co-Founder, Kisan Limited",
        "email": "kisanlimited@cropwise.demo",
        "phone": "+91 90000 55555",
        "location": "Raipur",
        "latitude": 21.2514, "longitude": 81.6296,
        "buyer_type": "processor",
        "verification_status": "verified",
        "reliability_score": 90.0,
        "payment_history_score": 91.0,
        "crops_of_interest": ["Tomato", "Onion", "Wheat", "Paddy (Rice)"],
    },
    {
        "company_name": "KisanKart",
        "email": "kisankart@cropwise.demo",
        "phone": "+91 90000 66666",
        "location": "Bilaspur",
        "latitude": 22.0797, "longitude": 82.1409,
        "buyer_type": "retailer",
        "verification_status": "verified",
        "reliability_score": 85.0,
        "payment_history_score": 87.0,
        "crops_of_interest": ["Tomato", "Onion", "Maize"],
    },
    {
        "company_name": "FarmLink Agro",
        "email": "farmlinkagro@cropwise.demo",
        "phone": "+91 90000 77777",
        "location": "Rajnandgaon",
        "latitude": 21.0972, "longitude": 81.0388,
        "buyer_type": "processor",
        "verification_status": "verified",
        "reliability_score": 83.0,
        "payment_history_score": 86.0,
        "crops_of_interest": ["Soybean", "Chana (Gram)", "Groundnut"],
    },
    {
        "company_name": "GreenRoute Foods",
        "email": "greenroutefoods@cropwise.demo",
        "phone": "+91 90000 88888",
        "location": "Mahasamund",
        "latitude": 21.1093, "longitude": 82.0980,
        "buyer_type": "wholesaler",
        "verification_status": "pending",
        "reliability_score": 70.0,
        "payment_history_score": 74.0,
        "crops_of_interest": ["Paddy (Rice)", "Maize", "Wheat"],
    },
    {
        "company_name": "Bharat Harvest",
        "email": "bharatharvest@cropwise.demo",
        "phone": "+91 90000 99999",
        "location": "Ambikapur",
        "latitude": 23.1200, "longitude": 83.1950,
        "buyer_type": "exporter",
        "verification_status": "verified",
        "reliability_score": 79.0,
        "payment_history_score": 82.0,
        "crops_of_interest": ["Maize", "Chana (Gram)", "Groundnut"],
    },
    {
        "company_name": "CropBridge",
        "email": "cropbridge@cropwise.demo",
        "phone": "+91 90001 00000",
        "location": "Korba",
        "latitude": 22.3595, "longitude": 82.7501,
        "buyer_type": "wholesaler",
        "verification_status": "verified",
        "reliability_score": 76.0,
        "payment_history_score": 80.0,
        "crops_of_interest": ["Wheat", "Paddy (Rice)"],
    },
]
