"""
Phase 3 — Official mandi-data synchronisation.

Pulls the LATEST AVAILABLE official records for one state (Maharashtra is
the primary showcase) from the providers CropWise already integrates with,
normalises them, and persists them as real `MarketPrice` rows tagged
`data_source="live"`.

WORDING (deliberate, do not "improve" this):
    The data.gov.in resource behind this is a DAILY mandi-price dataset.
    Call it "government-sourced daily mandi prices" -- never "real-time
    mandi prices". The most recent record available may legitimately be
    from a previous day, and that is what `observed_at` reports.

WHAT THIS SERVICE WILL NOT DO
-----------------------------
- It never invents a price, market, commodity, quantity or date. Only
  records the provider actually returned are stored.
- It never invents a timestamp. `observed_at` is whatever the provider
  reported (a date, usually, with no clock time -- stored as given). Only
  `fetched_at` is generated by CropWise, because CropWise genuinely knows
  when it performed the fetch.
- It never writes demo/seeded values into a `data_source="live"` row, and
  never rewrites an existing demo row into a live one. The two remain
  separately identifiable forever.
- A failed sync does NOT clear `last_successful_sync`. A stale-but-known
  state must stay distinguishable from a fresh one, so the last good
  timestamp is preserved and the failure is recorded beside it.

The crop list is NOT hard-coded to a wishlist. `sync_state()` asks for the
crops CropWise actually knows about (`CROPS`), and whatever the provider
has records for is what gets stored -- if the provider has no Potato
record for Maharashtra today, no Potato row appears. That is a real
absence, not an error.
"""
import datetime as dt
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Optional

from sqlalchemy.orm import Session

from app import models
from app.config import logger
from app.mock_data.crops import CROPS
from app.services import live_market_data
from app.services.mandi_source_normalization import to_source_state

# Provider identifier used in ProviderSyncState.provider and on every
# MarketPrice row this service writes. Matches the naming already used by
# mandi_directory's multi-source attribution so the two agree.
PROVIDER_DATA_GOV_IN = "data.gov.in"

# Maharashtra is the primary showcase state for the official-data pipeline.
DEFAULT_SYNC_STATE = "Maharashtra"

# Bounded fan-out: the provider is queried once per (crop, market) pair and
# those calls are independent, so they run concurrently -- same pattern and
# same reasoning as compare_markets(). Kept modest to stay polite to a
# government endpoint rather than to maximise throughput.
_MAX_SYNC_WORKERS = 8


def _utcnow() -> dt.datetime:
    """All persisted timestamps are UTC. Presentation-layer formatting
    (e.g. '15 Sep 2026, 3:15 PM' IST) is the frontend's job -- the database
    never stores a localised string."""
    return dt.datetime.utcnow()


def get_sync_state(db: Session, provider: str = PROVIDER_DATA_GOV_IN) -> Optional[models.ProviderSyncState]:
    return db.query(models.ProviderSyncState).filter_by(provider=provider).first()


def _get_or_create_sync_state(db: Session, provider: str, state: str) -> models.ProviderSyncState:
    row = get_sync_state(db, provider)
    if row is None:
        row = models.ProviderSyncState(provider=provider, state=state)
        db.add(row)
        db.flush()
    return row


def _persist_record(db: Session, crop: str, market: str, record: dict, fetched_at: dt.datetime) -> bool:
    """Upsert one provider record as a live MarketPrice row.

    Returns True if a row was created or updated. Matching is on
    (crop, market, date, data_source="live") so re-syncing the same day
    updates that day's row in place instead of accumulating duplicates --
    and so a live row can never collide with, or overwrite, a demo row for
    the same day.
    """
    observed_at = record.get("arrival_date")
    if observed_at is None:
        # No observation date from the provider means we cannot honestly
        # place this record in time. Skip rather than substituting today.
        logger.debug("mandi_sync: skipping %s/%s -- provider gave no arrival_date", crop, market)
        return False

    modal = record.get("modal_price")
    if modal is None:
        logger.debug("mandi_sync: skipping %s/%s -- provider gave no modal_price", crop, market)
        return False

    existing = (
        db.query(models.MarketPrice)
        .filter(
            models.MarketPrice.crop == crop,
            models.MarketPrice.market == market,
            models.MarketPrice.date == observed_at,
            models.MarketPrice.data_source == "live",
        )
        .first()
    )

    min_p = record.get("min_price")
    max_p = record.get("max_price")
    target = existing or models.MarketPrice(
        crop=crop, market=market, date=observed_at, data_source="live",
    )
    target.modal_price = modal
    # Fall back to the modal price only when the provider genuinely omits a
    # min/max -- these columns are NOT NULL. This is a representational
    # fallback for a missing bound, not an invented observation.
    target.min_price = min_p if min_p is not None else modal
    target.max_price = max_p if max_p is not None else modal
    # arrivals_tonnes stays NULL when the provider has no arrival volume;
    # a fabricated 0.0 would be indistinguishable from a real zero-arrival
    # day (see the MarketPrice model comment).
    target.arrivals_tonnes = record.get("quantity")
    target.source = PROVIDER_DATA_GOV_IN
    target.observed_at = observed_at
    target.fetched_at = fetched_at
    target.source_timestamp = record.get("fetched_at")

    if existing is None:
        db.add(target)
    return True


def sync_state(
    db: Session,
    state: str = DEFAULT_SYNC_STATE,
    crops: Optional[list] = None,
    markets: Optional[list] = None,
) -> dict:
    """
    Fetch → normalise → state-filter → persist, for one state.

    Returns a summary dict (never raises for a provider-side failure --
    an unreachable provider is an expected operating condition, not a
    crash):

        {
          "provider": "data.gov.in",
          "state": "Maharashtra",
          "status": "ok" | "not_configured" | "no_records" | "error",
          "records_synced": int,
          "pairs_attempted": int,
          "fetched_at": ISO-8601 UTC,
          "last_successful_sync": ISO-8601 UTC | None,
        }

    `status="no_records"` is a real, honest outcome meaning the provider
    responded but has nothing for this state right now -- distinct from
    `"error"` (the provider itself failed) and from `"not_configured"`
    (no API key, so nothing was even attempted).
    """
    attempted_at = _utcnow()
    sync_row = _get_or_create_sync_state(db, PROVIDER_DATA_GOV_IN, state)
    sync_row.last_attempted_sync = attempted_at
    sync_row.state = state

    if not live_market_data.is_configured():
        sync_row.last_error = "data.gov.in API key is not configured"
        db.commit()
        logger.info("mandi_sync: skipped -- provider not configured")
        return {
            "provider": PROVIDER_DATA_GOV_IN, "state": state, "status": "not_configured",
            "records_synced": 0, "pairs_attempted": 0,
            "fetched_at": attempted_at.isoformat() + "Z",
            "last_successful_sync": (
                sync_row.last_successful_sync.isoformat() + "Z"
                if sync_row.last_successful_sync else None
            ),
        }

    crop_names = crops if crops is not None else [c["name"] for c in CROPS]
    # Markets are resolved from what the provider itself reports for this
    # state -- not from CropWise's internal town list, which would quietly
    # bias the sync toward names the government dataset may not even use.
    if markets is None:
        from app.services import mandi_directory
        markets = mandi_directory.discover_state_markets(state)
    if not markets:
        sync_row.last_error = "no official market names discovered for this state"
        db.commit()
        logger.info("mandi_sync: no markets discovered for state=%s", state)
        return {
            "provider": PROVIDER_DATA_GOV_IN, "state": state, "status": "no_records",
            "records_synced": 0, "pairs_attempted": 0,
            "fetched_at": attempted_at.isoformat() + "Z",
            "last_successful_sync": (
                sync_row.last_successful_sync.isoformat() + "Z"
                if sync_row.last_successful_sync else None
            ),
        }

    pairs = [(c, m) for c in crop_names for m in markets]

    # Network fan-out only -- no DB session is touched inside the pool
    # (SQLAlchemy Sessions are not thread-safe). Results are persisted
    # afterwards on this thread, same split as compare_markets().
    results = []
    saw_error = False
    with ThreadPoolExecutor(max_workers=min(len(pairs), _MAX_SYNC_WORKERS)) as pool:
        future_map = {
            pool.submit(live_market_data.fetch_live_price_status, crop, market, state): (crop, market)
            for crop, market in pairs
        }
        for future in as_completed(future_map):
            crop, market = future_map[future]
            try:
                outcome = future.result()
            except Exception as e:  # provider/transport failure for this pair only
                logger.debug("mandi_sync: fetch failed for %s/%s: %s", crop, market, e)
                saw_error = True
                continue
            if outcome["status"] == "ok":
                results.append((crop, market, outcome["result"]))
            elif outcome["status"] == "error":
                saw_error = True

    fetched_at = _utcnow()
    synced = 0
    for crop, market, record in results:
        if _persist_record(db, crop, market, record, fetched_at):
            synced += 1

    if synced > 0:
        sync_row.last_successful_sync = fetched_at
        sync_row.records_synced = synced
        sync_row.last_error = None
        status = "ok"
    elif saw_error:
        # Preserve the previous last_successful_sync -- a failed attempt
        # must not erase the fact that we once had good data.
        sync_row.last_error = "provider request(s) failed; no records persisted"
        status = "error"
    else:
        sync_row.last_error = None
        status = "no_records"

    db.commit()
    logger.info(
        "mandi_sync: provider=%s state=%s status=%s pairs=%d synced=%d",
        PROVIDER_DATA_GOV_IN, state, status, len(pairs), synced,
    )
    return {
        "provider": PROVIDER_DATA_GOV_IN,
        "state": state,
        "status": status,
        "records_synced": synced,
        "pairs_attempted": len(pairs),
        "fetched_at": fetched_at.isoformat() + "Z",
        "last_successful_sync": (
            sync_row.last_successful_sync.isoformat() + "Z"
            if sync_row.last_successful_sync else None
        ),
    }


def freshness(db: Session, provider: str = PROVIDER_DATA_GOV_IN) -> dict:
    """Freshness summary for the data-source badge / admin view.

    `status` is about the PROVIDER's sync health, not about any one price:
      "never_synced"  -- no successful sync has ever completed
      "ok"            -- last sync succeeded
      "stale"         -- last attempt failed, but older good data exists
    """
    row = get_sync_state(db, provider)
    if row is None or row.last_successful_sync is None:
        return {
            "provider": provider, "status": "never_synced",
            "last_successful_sync": None, "last_attempted_sync": (
                row.last_attempted_sync.isoformat() + "Z"
                if row and row.last_attempted_sync else None
            ),
            "last_error": row.last_error if row else None,
            "records_synced": None,
        }
    return {
        "provider": provider,
        "status": "stale" if row.last_error else "ok",
        "last_successful_sync": row.last_successful_sync.isoformat() + "Z",
        "last_attempted_sync": (
            row.last_attempted_sync.isoformat() + "Z" if row.last_attempted_sync else None
        ),
        "last_error": row.last_error,
        "records_synced": row.records_synced,
    }
